core/urls.py
from django.urls import path
from . import views

# create new url
urlpatterns = [
    # home url 
    path('', views.index, name='index'),
    # # login
    # path('login', views.login, name='login'),
    # # signup
    # path('signup' , views.signup, name='signup'),
    # # movie path with specific 
    # path('movie/<str:pk>/' , views.movie, name='movie'),
    # # list genere with specific 
    # path('genre/<str:pk>/' , views.genre, name='genre'),
    # # my fav list
    # path('my-list', views.my_list, name='my-list'),
    # # add to list 
    # path('add-to-list' , views.add_to_list, name='add-to-list'),
    # # search
    # path('search', views.search, name='search'),
]

nextflick_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
import uuid
from django.conf import settings

# Create your models here.
class Movie(models.Model):

    GENRE_CHOICES = [
        ('action', 'Action'),
        ('comedy', 'Comedy'),
        ('drama', 'Drama'),
        ('horror', 'Horror'),
        ('romance', 'Romance'),
        ('science_fiction', 'Science Fiction'),
        ('fantasy', 'Fantasy'),
    ]

    uu_id = models.UUIDField(default=uuid.uuid4)
    title = models.CharField(max_length=255)
    description = models.TextField()
    release_date = models.DateField()
    genre = models.CharField(max_length=100, choices=GENRE_CHOICES)
    length = models.PositiveIntegerField()
    image_card = models.ImageField(upload_to='movie_images/')
    image_cover = models.ImageField(upload_to='movie_images/')
    video = models.FileField(upload_to='movie_videos/')
    movie_views = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    
class MovieList(models.Model):
    owner_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

core/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    #rendering html file
    return render(request, 'index.html')


    

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NextFlick</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>

<body class="text-white" style="background-color: #141414;">
    <header class="p-5 flex justify-between items-center">
        <img src="media/movie_images/nextflick-logo.png" height="30" alt="NextFlick Logo" width="250">

        <nav class="flex apce-x-5">
            <span><a href="/">Home</a></span>

            <div class="dropdown">
                <span id="dropdownMenuButton" class="cursor-pointer">Lists ▼</span>

                <div id="dropdownMenu" class="dropdown-content hidden">
                    <ul><a href="/lists/action">Action</a></ul>
                    <ul><a href="/lists/comedy">Comedy</a></ul>
                    <ul><a href="/lists/drama">Drama</a></ul>
                    <ul><a href="/lists/horror">Horror</a></ul>
                    <ul><a href="/lists/romance">Romance</a></ul>
                    <ul><a href="/lists/sciencefiction">Science Fiction</a></ul>
                    <ul><a href="/lists/fantacy">Fantacy</a></ul>
                </div>

            </div>

            <span><a href="/my-list">My List</a></span>
        </nav>

        <div class="flex space-x-5" items-center>
            <form action='search' method="POST">
                {% csrf_token %}
                <input type="search" name='search_term' placeholder="Search" class="bg-grey-700 p-2 rounded">
                <button class="bg-red-600 test-white p-2 rounded hover:bg-red=500">Search</button>
            </form>
            <div class="relative">
                <a href="#" class="block p-2">Welcome , {{user.username}}</a>
                <a href="/logout" c;ass="block p-2">Logout</a>
            </div>
        </div>
    </header>

    <section class="relative py-20 px-10" style="background-image: url('{{featured_movie.image_cover.url}}'); background-size: cover;">
        <div>
            <h1 style="color: black;" class="text-5xl mb-5">{{featured_movie.title}}</h1>
            <p style="color: black;" class="mb-5">{{featured_movie.description}}<</p>
            <div class="flex space-x-4">
                <a href="/movie/{{featured_movie.uu_id}}">
                    <button class="bg-red-600 text-white p-2 px-5 rounded hover:bg-red-500">Play</button>
                </a>
            </div>
        </div>
    </section>

    <section class="py-10 px-5">
        <h2 class="text-xl mb-5">Popular on NextFlick</h2>
        <div class="flex space-x-5 overflow-x-auto">
            {% for movie in movies %}
            <divclass="w-40 h-64 flex-shrink-0 film-card"
                onclick="showModal(this)" 
                data-title="{{ movie.title }}"
                data-description="{{ movie.description }}"
                data-release-date="{{ movie.release_date|date:'Y' }}"
                data-genre="{{ movie.get_genre_display }}" 
                data-length="{{ movie.length }}"
                data-image-card-url="{{ movie.image_card.url }}"
                data-image-cover-url="{{ movie.image_cover.url }}"
                data-video-url="/movie/{{ movie.uu_id }}"
                style="background-image: url('{{movie.image_card.url}}'); background-size: cover; background-position: center;">
            </div>
            {% endfor %}
        </div>
    </section>

    {% comment %} Modal {% endcomment %}
    <div class="modal" id="movieModal">
        <div class="modal-content">
            <div class="flex justify-between">
                <h2 class="text-xl mb-5">Movie Title</h2>
                {% comment %} onclick function  {% endcomment %}
                <button onclick="hideModal()">X</button>
            </div>
            <img width="1000" height="100" src="https://dunenewsnet.com/wp-content/uploads/2021/08/Dune-Movie-Official-Poster-banner-feature-770x364.jpg.webp" alt="Movie Image" class=" mb-5">
            <div class="flex justify-between mb-5">
                <span>Year: 2024</span>
                <span>Length: 2h 15min</span>
            </div>
            <p class="mb-5">Detailed information about the movie.</p>
            <div class="flex space-x-4 mb-5">
                <a href="movie.html">
                    <button class="bg-red-600 text-white p-2 px-5 rounded hover:bg-red-500">Play</button>
                </a>
                 <button id="addToListButton" onclick="addItemToList()" class="border border-white text-white p-2 px-5 rounded hover:bg-gray-700">
                    Add to List
                </button>
            </div>
        </div>
    </div>

   {% comment %} JavaScript code {% endcomment %}
    <script>
        // function to retrieve data attribute
        function showModal(element) {
            //retrieve data attribute 
            const title = element.getAttibute('data-title');
            const description = element.getAttibute('data-description');
            const releaseDate = element.getAttibute('data-release-date');
            const genre = element.getAttibute('data-genre');
            const length = element.getAttibute('data-length');
            const imageCardUrl = element.getAttibute('data-image-card-url');
            const imageCoverUrl = element.getAttibute('data-image-cover-url');
            const dataVideoUrl = element.getAttibute('data-video-url');

           // update the modal's content with the movie details 
            const modal = document.getElementById('movieModal');
            modal.querySelector('.modal-content h2').textContent = title;
            modal.querySelector('.modal-content img').src = imageCoverUrl;
            modal.querySelector('.modal-content a').href = dataVideoUrl;  
            modal.querySelector('.modal-content img').alt = title + " Cover Image";
            modal.querySelector('.modal-content .flex span:first-child').textContent = "Year: " + releaseDate;
            modal.querySelector('.modal-content .flex span:nth-child(2)').textContent = "Genre: " + genre;
            modal.querySelector('.modal-content .flex span:last-child').textContent = "Length: " + length + "min";
            modal.querySelector('.modal-content p').textContent = description;

            // show the modal 
            modal.style.display = 'block';
            // use set timeout 
            setTimout(() => {
                modal.classList.add('modal-show');
            }, 50);
        }

        //onclick function hideModal
        function hideModal() {
            const modal = document.querySelector('.modal');
            modal.classList.remove('modal-show');
            setTimout(() => {
                modal.style.display = 'none';
            }, 300);
        }

        window.onclick = function(event) {
            if (event.target === document.getElementById('movieModal')) {
                // if yes, call hideModal function 
                hideModal();
            }
        }

        {% comment %} waiting for core/urls and core/views to be done implementation first then call the function
        // function add item to the fav list 
        function addItemToList() {
            const modal = document.getElementById('movieModal');
            let movieId = modal.querySelector('.modal-content a').href;

            // jQuery POST method  
             $.ajax({
                url: "{% url 'add-to-list' %}",
                type: "POST",
                data: {
                    movie.id: movieId,
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                },
                success: function(data) {
                    $('#addToListButton').text(data.message);
                    
                    $('addToListButton')prop('disabled' , true);

                    console.log('Item added to List!');
                },
                error: function(xhr, errmsg, err) {
                    console.error("Error adding item to list: " + errmsg);
                }
            });
        }
        {% endcomment %}


    </script>

</body>